In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# custom index

In [ ]:

groups=["CSE","ICE","ETE","EEE"]
id=[1,2,9,101]
pd.Series(group,index=[1,2,9,101])

1      CSE
2      ICE
9      ETE
101    EEE
dtype: object

In [ ]:
#Adding name

groups=["CSE","ICE","ETE","EEE"]
id=[1,2,9,101]
new_team=pd.Series(groups,index=id,name='New Groups Member')

In [ ]:
new_team

1      CSE
2      ICE
9      ETE
101    EEE
Name: New Groups Member, dtype: object

In [ ]:
#using dictionary

In [ ]:
team={'Football':1,
      'HandBall':2,
      'Cricket':3,
      'Buskatball':4
      }

In [ ]:
list_games=pd.Series(team,name="Games list")
list_games

Football      1
HandBall      2
Cricket       3
Buskatball    4
Name: Games list, dtype: int64

In [ ]:
list_games.size

4

In [ ]:
list_games.name

'Games list'

In [ ]:
list_games.dtype

dtype('int64')

In [ ]:
list_games.is_unique

True

In [ ]:
pd.Series(["A","b","A","C","D","C"]).is_unique

False

In [ ]:
list_games.index

Index(['Football', 'HandBall', 'Cricket', 'Buskatball'], dtype='object')

In [ ]:
list_games.values

array([1, 2, 3, 4])

#Series using read_csv

In [ ]:

pd.read_csv('/content/Best Universities for Engineering & Technology on BachelorsPortal.csv',squeeze=True)

,University_link,University_Name,Location,T.H.E.R (2018),Top.U.R(2018),U.S. News & World Report.R(2018)
0,https://www.bachelorsportal.com/universities/1...,University of Chicago,"Chicago, United States",-,125,105
1,https://www.bachelorsportal.com/universities/1...,New York University,"New York City, United States",-,132,151
2,https://www.bachelorsportal.com/universities/3...,University of Amsterdam,"Amsterdam, Netherlands",-,132,389
3,https://www.bachelorsportal.com/universities/2...,University of Copenhagen,"Copenhagen, Denmark",-,132,-
4,https://www.bachelorsportal.com/universities/1...,University Kebangsaan Malaysia,"Semenyih, Malaysia",-,135,168
...,...,...,...,...,...,...
1464,https://www.bachelorsportal.com/universities/1...,"University of California, Berkeley","Berkeley, United States",13,8,5
1465,https://www.bachelorsportal.com/universities/1...,Carnegie Mellon University,"Pittsburgh, United States",12,31,51
1466,https://www.bachelorsportal.com/universities/1...,Georgia Institute of Technology,"Atlanta, United States",11,16,14
1467,https://www.bachelorsportal.com/universities/1...,Imperial College London,"London, United Kingdom",10,6,9
1468,https://www.bachelorsportal.com/universities/3...,ETH Zurich - Swiss Federal Institute of Techno...,"Zürich, Switzerland",9,5,12

In [ ]:
pd.read_csv('/content/DeviceSpecs.com all category smarthphone ads.csv.csv',index_col='Currency',squeeze=True)

,Products_link,Products_Model,Products_details,Price_regular,Price_offers,Known_price
Currency,,,,,,
EUR,https://www.device-specs.io/categories/smartph...,Apple iPhone Xs Max,2018 - 6 cores - 6.5 inch - 256GB - space grey...,899.00,799,1
EUR,https://www.device-specs.io/categories/smartph...,Oppo A16s,2021 - 8 cores - 6.52 inch - 64GB - Black - 59...,179.38,169,1
NaN,https://www.device-specs.io/categories/smartph...,Huawei Y5,2019 - 4 cores - 5.71 inch - 16GB - black - 51...,144.00,NaN,1
NaN,https://www.device-specs.io/categories/smartph...,Apple iPhone 11 Pro Max,6 cores - 6.5 inch - 256GB - Silver - MWHK2ZD/A,536.00,,1
NaN,https://www.device-specs.io/categories/smartph...,Apple iPhone 11 Pro Max,6 cores - 6.5 inch - 64GB - Gold - MWHG2ZD/A,486.00,,1
...,...,...,...,...,...,...
NaN,https://www.device-specs.io/categories/smartph...,Apple iPhone 12,2020 - A14 Bionic Chip - 6 cores - 6.1 inch - ...,731.00,,3
NaN,https://www.device-specs.io/categories/smartph...,Samsung Galaxy A53,2022 - Samsung Exynos 1280 - 8 cores - 6.5 inc...,417.45,,4
NaN,https://www.device-specs.io/categories/smartph...,Samsung Galaxy A53,2022 - Samsung Exynos 1280 - 8 cores - 6.5 inc...,377.41,,3
NaN,https://www.device-specs.io/categories/smartph...,Samsung Galaxy A52S,Qualcomm Snapdragon - 8 cores - 6.5 inch - 128...,364.26,,1
EUR,https://www.device-specs.io/categories/smartph...,Samsung Galaxy Xcover 5,2021 - Samsung Exynos 850 - 8 cores - 5.3 inch...,271.00,263.99,3

In [ ]:
smartphones=pd.read_csv('/content/DeviceSpecs.com all category smarthphone ads.csv.csv',index_col='Products_link',squeeze=True)

In [ ]:
smartphones

,Products_Model,Products_details,Price_regular,Price_offers,Currency,Known_price
Products_link,,,,,,
https://www.device-specs.io/categories/smartphones/specifications-apple-iphone-xs-max-app-xsm256gr3,Apple iPhone Xs Max,2018 - 6 cores - 6.5 inch - 256GB - space grey...,899.00,799,EUR,1
https://www.device-specs.io/categories/smartphones/specifications-oppo-a16s-5996496,Oppo A16s,2021 - 8 cores - 6.52 inch - 64GB - Black - 59...,179.38,169,EUR,1
https://www.device-specs.io/categories/smartphones/specifications-huawei-y5-51093shg,Huawei Y5,2019 - 4 cores - 5.71 inch - 16GB - black - 51...,144.00,NaN,NaN,1
https://www.device-specs.io/categories/smartphones/specifications-apple-iphone-11-pro-max-mwhk2zda,Apple iPhone 11 Pro Max,6 cores - 6.5 inch - 256GB - Silver - MWHK2ZD/A,536.00,,NaN,1
https://www.device-specs.io/categories/smartphones/specifications-apple-iphone-11-pro-max-mwhg2zda,Apple iPhone 11 Pro Max,6 cores - 6.5 inch - 64GB - Gold - MWHG2ZD/A,486.00,,NaN,1
...,...,...,...,...,...,...
https://www.device-specs.io/categories/smartphones/specifications-apple-iphone-12-mgj63zda,Apple iPhone 12,2020 - A14 Bionic Chip - 6 cores - 6.1 inch - ...,731.00,,NaN,3
https://www.device-specs.io/categories/smartphones/specifications-samsung-galaxy-a53-sm-a536bzkneeb,Samsung Galaxy A53,2022 - Samsung Exynos 1280 - 8 cores - 6.5 inc...,417.45,,NaN,4
https://www.device-specs.io/categories/smartphones/specifications-samsung-galaxy-a53-sm-a536bzkneub,Samsung Galaxy A53,2022 - Samsung Exynos 1280 - 8 cores - 6.5 inc...,377.41,,NaN,3
https://www.device-specs.io/categories/smartphones/specifications-samsung-galaxy-a52s-sm-a528bzkdeeb,Samsung Galaxy A52S,Qualcomm Snapdragon - 8 cores - 6.5 inch - 128...,364.26,,NaN,1
https://www.device-specs.io/categories/smartphones/specifications-samsung-galaxy-xcover-5-sm-g525fzkdeeb,Samsung Galaxy Xcover 5,2021 - Samsung Exynos 850 - 8 cores - 5.3 inch...,271.00,263.99,EUR,3

#Series Methods

In [ ]:
smartphones.head()

,Products_Model,Products_details,Price_regular,Price_offers,Currency,Known_price
Products_link,,,,,,
https://www.device-specs.io/categories/smartphones/specifications-apple-iphone-xs-max-app-xsm256gr3,Apple iPhone Xs Max,2018 - 6 cores - 6.5 inch - 256GB - space grey...,899.00,799,EUR,1
https://www.device-specs.io/categories/smartphones/specifications-oppo-a16s-5996496,Oppo A16s,2021 - 8 cores - 6.52 inch - 64GB - Black - 59...,179.38,169,EUR,1
https://www.device-specs.io/categories/smartphones/specifications-huawei-y5-51093shg,Huawei Y5,2019 - 4 cores - 5.71 inch - 16GB - black - 51...,144.00,NaN,NaN,1
https://www.device-specs.io/categories/smartphones/specifications-apple-iphone-11-pro-max-mwhk2zda,Apple iPhone 11 Pro Max,6 cores - 6.5 inch - 256GB - Silver - MWHK2ZD/A,536.00,,NaN,1
https://www.device-specs.io/categories/smartphones/specifications-apple-iphone-11-pro-max-mwhg2zda,Apple iPhone 11 Pro Max,6 cores - 6.5 inch - 64GB - Gold - MWHG2ZD/A,486.00,,NaN,1

In [ ]:
smartphones.head(5
                 )

,Products_Model,Products_details,Price_regular,Price_offers,Currency,Known_price
Products_link,,,,,,
https://www.device-specs.io/categories/smartphones/specifications-apple-iphone-xs-max-app-xsm256gr3,Apple iPhone Xs Max,2018 - 6 cores - 6.5 inch - 256GB - space grey...,899.00,799,EUR,1
https://www.device-specs.io/categories/smartphones/specifications-oppo-a16s-5996496,Oppo A16s,2021 - 8 cores - 6.52 inch - 64GB - Black - 59...,179.38,169,EUR,1
https://www.device-specs.io/categories/smartphones/specifications-huawei-y5-51093shg,Huawei Y5,2019 - 4 cores - 5.71 inch - 16GB - black - 51...,144.00,NaN,NaN,1
https://www.device-specs.io/categories/smartphones/specifications-apple-iphone-11-pro-max-mwhk2zda,Apple iPhone 11 Pro Max,6 cores - 6.5 inch - 256GB - Silver - MWHK2ZD/A,536.00,,NaN,1
https://www.device-specs.io/categories/smartphones/specifications-apple-iphone-11-pro-max-mwhg2zda,Apple iPhone 11 Pro Max,6 cores - 6.5 inch - 64GB - Gold - MWHG2ZD/A,486.00,,NaN,1

In [ ]:
smartphones.tail(2)

,Products_Model,Products_details,Price_regular,Price_offers,Currency,Known_price
Products_link,,,,,,
https://www.device-specs.io/categories/smartphones/specifications-samsung-galaxy-a52s-sm-a528bzkdeeb,Samsung Galaxy A52S,Qualcomm Snapdragon - 8 cores - 6.5 inch - 128...,364.26,,NaN,1
https://www.device-specs.io/categories/smartphones/specifications-samsung-galaxy-xcover-5-sm-g525fzkdeeb,Samsung Galaxy Xcover 5,2021 - Samsung Exynos 850 - 8 cores - 5.3 inch...,271.00,263.99,EUR,3

In [ ]:
smartphones.sample()

,Products_Model,Products_details,Price_regular,Price_offers,Currency,Known_price
Products_link,,,,,,
https://www.device-specs.io/categories/smartphones/specifications-samsung-galaxy-note10-sm-n970f-sm-n970fzsdphe,Samsung Galaxy Note10 SM-N970F,2019 - 8 cores - 6.3 inch - 256GB - Multicolor...,699.0,,NaN,1

In [ ]:
smartphones.sample(2)

,Products_Model,Products_details,Price_regular,Price_offers,Currency,Known_price
Products_link,,,,,,
https://www.device-specs.io/categories/smartphones/specifications-apple-iphone-14-pro-max-mq8p3lla,Apple iPhone 14 Pro Max,"A16 Bionic chip, 6-core CPU with 2 performance...",1099.99,,NaN,1
https://www.device-specs.io/categories/smartphones/specifications-doro-8100-4g-simple-senior-8383,Doro 8100 4G Simple Senior,2022 - 8 cores - 6.1 inch - 32GB - Black - 8383,324.95,,NaN,1

In [ ]:
smartphones.value_counts()

Products_Model        Products_details                                                                        Price_regular  Price_offers  Currency  Known_price
Alcatel 1             2021 - 4 cores - 5 inch - 8GB - Black - 5033DR-2AALWE12-1                               81.45          80.85         EUR       1              1
Samsung Galaxy M32    2021 - 8 cores - 6.4 inch - 128GB - White - SM-M325FZWGEUB                              253.20         250           EUR       1              1
Samsung Galaxy A7     2018 - 8 cores - 6 inch - 64GB - Black - SM-A750FZKUPHN                                 289.00         269           EUR       1              1
Samsung Galaxy A71    Snapdragon 365 - 6.7 inch - 128GB - Prism Cube Black - SM-A716U                         499.99         20.84         USD       1              1
Samsung Galaxy A73    2022 - 8 cores - 6.7 inch - 128GB - Gray - SM-A736B/DS                                  540.00         538           EUR       1              1
                                                                                                                                                                   ..
Cat B30               2 inch - 256GB - Black - CB30-DSGE-E02-EBB                                              85.00          49.99         EUR       1              1
Cat S42H+             2021 - MediaTek - 4 cores - 5.5 inch - 32GB - Black - CS42H-DAB-RON-NN                  258.00         236           EUR       3              1
Cat S60               2016 - 4 cores - 4.7 inch - 32GB - Black - CS60-DEB-EUR-KN                              419.99         269           EUR       1              1
Cat S62 Pro           2020 - Qualcomm Snapdragon 660 - 8 cores - 5.7 inch - 128GB - Black - CS62P-DAB-RON-EN  650.00         609           EUR       3              1
Xiaomi Redmi Note 9T  2021 - 8 cores - 6.53 inch - 128GB - Black - MZB084MEU                                  277.00         274           EUR       1              1
Length: 888, dtype: int64